# #
#   @ref        https://api.docs.cpanel.net/guides/guide-to-whm-plugins/guide-to-whm-plugins-appconfig-configuration-file
#               https://api.docs.cpanel.net/guides/guide-to-cpanel-plugins/guide-to-cpanel-plugins-add-plugins
# #

# name
name=csf

# https://support.cpanel.net/hc/en-us/community/posts/19122386766743-Customize-App-Integration
implements=csf

# Service that will serve this app
service=whostmgr
 
# Physical path: /usr/local/cpanel/3rdparty/Foo.php
# Literal URL path: $server:$port/$cpsession/3rdparty/Foo.php
url=/cgi/configserver/csf.cgi
 
# System user to run process as
user=root

# Required acls
acls=software-ConfigServer-csf

# Display name as show in the service ui
displayname=ConfigServer Security & Firewall

# Url to show in the service ui (relative to install path for whm this is cgi/)
entryurl=configserver/csf.cgi

# Path to upgrade script
upgradecall=/usr/local/cpanel/whostmgr/docroot/cgi/configserver/csf/upgrade.sh

# Space-separated list of Keywords for WHM search (cPanel & WHM version 132 (132.0.0) and later.)
searchtext=CSF ConfigServer Firewall Security Iptables Nftables

icon=csf_small.png

# _blank or _self
target=_self

vendor=Aetherinox
